#!/bin/bash
# ---------------------------------------------------------------------------
#
# Usage: . continue-jobline jobline_no sync_mode
#
# Description: Continues a jobline by adjusting the latest job script and submitting
# it to the batchsystem.
#
# Option: sync_mode
#    Possible values: 
#        sync: The sync-control-jobfile script is called
#        anything else: no synchronization
#
# Revision history:
# 2015-12-05  Created (version 1.2)
# 2015-12-12  Various improvements (version 1.10)
# 2015-12-16  Adaption to version 2.1
# 2016-07-16  Various improvements
#
# ---------------------------------------------------------------------------
# Displaying help if the first argument is -h
usage="Usage: . continue-jobline jobline_no sync_mode"
if [ "${1}" == "-h" ]; then
   echo -e "\n${usage}\n\n"
   exit 0 
fi
if [[ "$#" -ne "2" ]]; then
   echo -e "\nWrong number of arguments. Exiting."
   echo -e "\n${usage}\n\n"
   exit 1
fi

# Standard error response 
error_response_nonstd() {
    echo "Error was trapped which is a nonstandard error."
    echo "Error in bash script $(basename ${BASH_SOURCE[0]})"
    echo "Error on line $1"
    exit 1
}
trap 'error_response_nonstd $LINENO' ERR

# Variables
# Getting the batchsystem type
batchsystem="$(grep -m 1 "^batchsystem=" ../../workflow/control/all.ctrl | tr -d '[[:space:]]' | awk -F '[=#]' '{print $2}')"
sync_mode=${2}

# Getting the jobline number and the old job number
jobline_no=${1}
if [ "${batchsystem}" = "SLURM" ]; then
    line=$(cat ../../workflow/job-files/main/${jobline_no}.job | grep -m 1 "job-name")
    old_job_no=${line/^#SBATCH --job-name=[a-zA-Z]-}
elif [ "${batchsystem}" = "MTP" ]; then
    line=$(cat ../../workflow/job-files/main/${jobline_no}.job | grep -m 1 "\-N")
    old_job_no=${line/^\#PBS -N [a-zA-Z]-}
elif [ "${batchsystem}" = "SGE" ]; then
    line=$(cat ../../workflow/job-files/main/${jobline_no}.job | grep -m 1 "\-N")
    old_job_no=${line/^\#\$ -N [a-zA-Z]-}
elif [ "${batchsystem}" = "LSF" ]; then
    line=$(cat ../../workflow/job-files/main/${jobline_no}.job | grep -m 1 "^#BSUB \-J")
    old_job_no=${line/^\#BSUB -J [a-zA-Z]-}
fi
old_job_no_2=${old_job_no/*.}


# Computing the new job number
new_job_no_2=$((${old_job_no_2} + 1))
new_job_no="${jobline_no}.${new_job_no_2}"


# Syncing the workflow settings if specified
if [ "${sync_mode}" == "sync" ]; then
    . sync-jobfile ${jobline_no}
fi

# Changing the job number 1.1 (of template/new job file) to current job number
if [ "${batchsystem}" = "SLURM" ]; then
    sed -i "s/^#SBATCH --job-name=\([a-zA-Z]\)-.*/#SBATCH --job-name=\1-${new_job_no}/g"  ../../workflow/job-files/main/${jobline_no}.job
elif [ "${batchsystem}" = "MTP" ]; then
    sed -i "s/^#PBS -N \([a-zA-Z]\)-.*/#PBS -N \1-${new_job_no}/g"  ../../workflow/job-files/main/${jobline_no}.job
elif [ "${batchsystem}" = "LSF" ]; then
    sed -i "s/^#BSUB -J \([a-zA-Z]\)-.*/#BSUB -J \1-${new_job_no}/g"  ../../workflow/job-files/main/${jobline_no}.job
elif [ "${batchsystem}" = "SGE" ]; then
    sed -i "s/^#\\$ -N \([a-zA-Z]\)-.*/#\$ -N \1-${new_job_no}/g"  ../../workflow/job-files/main/${jobline_no}.job
fi

# Changing the output filenames
if [ "${batchsystem}" = "SLURM" ]; then
    sed -i "s|^#SBATCH --output=.*|#SBATCH --output=../workflow/output-files/jobs/job-${new_job_no}_%j.out|g"  ../../workflow/job-files/main/${jobline_no}.job
    sed -i "s|^#SBATCH --error=.*|#SBATCH --output=../workflow/output-files/jobs/job-${new_job_no}_%j.out|g"  ../../workflow/job-files/main/${jobline_no}.job
elif [ "${batchsystem}" = "MTP" ]; then
    sed -i "s|^#PBS -\([oe]\) .*|#PBS -\1 ../workflow/output-files/jobs/job-${new_job_no}_\${PBS_JOBID}.out|g"  ../../workflow/job-files/main/${jobline_no}.job
elif [ "${batchsystem}" = "SGE" ]; then
    sed -i "s|^#\\$ -\([oe]\) .*|#\$ -\1 ../workflow/output-files/jobs/job-${new_job_no}_\${PBS_JOBID}.out|g"  ../../workflow/job-files/main/${jobline_no}.job
elif [ "${batchsystem}" = "LSF" ]; then
    sed -i "s|^#BSUB -oo .*|#BSUB -oo ../workflow/output-files/jobs/job-${new_job_no}_%J.out|g"  ../../workflow/job-files/main/${jobline_no}.job
fi


# Submitting new job
. submit ../workflow/job-files/main/${jobline_no}.job
