#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Slurm-side inference bridge for the optional ML tranche-prioritization classifier.

one-queue.sh (a Bash script) cannot run PyTorch directly, so it shells out to this small CLI once
per collection (not once per ligand -- loading a model and importing torch/rdkit per ligand would
be a severe performance antipattern across a collection's hundreds-to-thousands of ligands),
passing every ligand's name and SMILES in a single input file and reading back one decision per
ligand.

Usage:
    python3 templates/ml_classifier_predict.py \\
        --model-path <path/to/model.pt> \\
        --probability-cutoff 0.5 \\
        --input-tsv  <collection_dir>/_ml_classifier_input.tsv \\
        --output-tsv <collection_dir>/_ml_classifier_decisions.tsv

Input TSV format: one row per ligand, `ligand_name<TAB>smiles` (smiles may be empty, meaning the
SMILES could not be extracted from that ligand's structure file).

Output TSV format: exactly one row per input row (rows are never dropped), in input order:
`ligand_name<TAB>KEEP|DISCARD<TAB>probability_or_NA`. Ligands with an empty/unparsable SMILES are
always written as DISCARD/NA (fail-closed).

Exit codes: 0 only if the output file was fully written with one row per input row. Non-zero on
any hard failure (model missing/corrupt, input file missing/unreadable), with an actionable
message on stderr.

@author: akshat
"""
import os
import sys
import csv
import argparse

from ml_classifier import load_classifier, filter_smiles_mask


def read_input_tsv(input_tsv_path):
    """
    Reads the per-collection ligand-name/SMILES input file.

    Malformed rows (wrong field count) are skipped with a stderr warning rather than aborting the
    whole run -- this file is machine-generated by one-queue.sh in the same job, so malformed rows
    should be rare/impossible, but defensive parsing is cheap insurance.

    Returns:
        list of (ligand_name, smiles) tuples, in file order.
    """
    rows = []
    with open(input_tsv_path, 'r', newline='') as f:
        reader = csv.reader(f, delimiter='\t')
        for line_number, fields in enumerate(reader, start=1):
            if len(fields) != 2:
                print('WARNING: Skipping malformed input row {}:{}: {}'.format(
                    input_tsv_path, line_number, fields), file=sys.stderr)
                continue
            rows.append((fields[0], fields[1]))
    return rows


def write_output_tsv_atomic(output_tsv_path, decisions):
    """
    Writes the decisions file atomically (temp file + os.replace), so a Bash-side reader can never
    observe a partially-written output file.

    Args:
        output_tsv_path (str): destination path.
        decisions (list of (ligand_name, decision, probability_str)): rows to write, in order.
    """
    out_dir = os.path.dirname(output_tsv_path)
    if out_dir != '' and not os.path.exists(out_dir):
        os.makedirs(out_dir, exist_ok=True)

    tmp_path = '{}.tmp-{}'.format(output_tsv_path, os.getpid())
    with open(tmp_path, 'w', newline='') as f:
        # lineterminator explicitly set to '\n': csv.writer defaults to '\r\n', which would leave
        # a stray '\r' at the end of each row's last field -- harmless in Python, but a Bash-side
        # reader doing `grep|awk` on this file would pick up that '\r' as part of the probability
        # field.
        writer = csv.writer(f, delimiter='\t', lineterminator='\n')
        for row in decisions:
            writer.writerow(row)
    os.replace(tmp_path, output_tsv_path)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--model-path', required=True, help='Path to the trained classifier (.pt file).')
    parser.add_argument('--probability-cutoff', type=float, default=0.5,
                        help='Minimum predicted probability (exclusive) to KEEP a ligand.')
    parser.add_argument('--input-tsv', required=True, help='Path to the ligand_name<TAB>smiles input file.')
    parser.add_argument('--output-tsv', required=True, help='Path to write ligand_name<TAB>decision<TAB>probability to.')
    args = parser.parse_args()

    try:
        model, metadata = load_classifier(args.model_path)
    except Exception as e:
        print('ERROR: Could not load ML classifier from {} ({}). '
              'Train one first with: python3 train_ml_classifier.py'.format(args.model_path, e), file=sys.stderr)
        return 1

    if not os.path.isfile(args.input_tsv):
        print('ERROR: Input TSV not found: {}'.format(args.input_tsv), file=sys.stderr)
        return 1

    try:
        rows = read_input_tsv(args.input_tsv)
    except Exception as e:
        print('ERROR: Could not read input TSV {} ({})'.format(args.input_tsv, e), file=sys.stderr)
        return 1

    ligand_names = [name for name, _ in rows]
    smiles_list = [smi for _, smi in rows]

    fp_radius = metadata.get('fp_radius', 2)
    fp_nbits = metadata.get('fp_nbits', 1024)
    keep_mask, probabilities = filter_smiles_mask(
        model, smiles_list, probability_cutoff=args.probability_cutoff,
        fp_radius=fp_radius, fp_nbits=fp_nbits)

    decisions = []
    for ligand_name, keep, probability in zip(ligand_names, keep_mask, probabilities):
        decision = 'KEEP' if keep else 'DISCARD'
        probability_str = '{:.6f}'.format(probability) if probability is not None else 'NA'
        decisions.append((ligand_name, decision, probability_str))

    try:
        write_output_tsv_atomic(args.output_tsv, decisions)
    except Exception as e:
        print('ERROR: Could not write output TSV {} ({})'.format(args.output_tsv, e), file=sys.stderr)
        return 1

    return 0


if __name__ == '__main__':
    sys.exit(main())
